name: Publish Java Package to GitHub Packages

on:
  release:
    types: [created] # Triggers when a new release is created.

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required permission to publish packages.

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          server-id: github # Must match the id in your pom.xml distributionManagement.
          settings-path: ${{ github.workspace }} # Location of the settings.xml file

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }} # The secret is automatically available.
